version: '3'

services:
    database:
        image: mysql
        restart: always
        environment: 
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=pony_express"
        volumes:
            - "/var/lib/mysql"
            - "./dump:/docker-entrypoint-initdb.d"
        ports: 
            - "3307:3306"
    api:
        image: "alexkalak/calculator-api"
        restart: always
        ports: 
            - "80:80"
        environment:
            - "DB_USR=root"
            - "DB_PASS=root"
            - "PORT=80"
            - "HOST=localhost"
            - "DB_SERV=db"
            - "DB_NAME=pony_express"
            - "DB_PORT=3306"
        links:
            - "database:db"
        depends_on:
            - "database"
